language: node_js
node_js:
- 6.9.0

sudo: required
dist: trusty

script:
- gulp build
- gulp package

before_install:
  - openssl aes-256-cbc -K $encrypted_5f819ac0d0f8_key -iv $encrypted_5f819ac0d0f8_iv -in .travis/github_deploy_key.enc -out github_deploy_key -d

env:
  global:
    - secure: "fLcBuV72stc6XRexM9uziwwoql9IIeWwSSzs84/PRwKlM7NrQ+wcsBJ+fR8FN4d9uWlHHkb9sw/rpA5KK0u5COd5HVRx56S+mN2DZO1ihZIElJBARAgLzPrNJ69Nm+z4EET+fCwyDwzAwFjrSetF9+QOwmyUO8vllGoM3TZMEhtZU+9OnehErGTYqk0FU6dkXuIv7zoXCzqukMFIK0txq6TdCSOooodRNkdqkHUlPE/8BSnG/RRD2l9qpR2n/rvnVmTpgCLrfxsclb0WfzpHNIZvi45en4GM2a+wRxfM4/F+bap8zufWN4dqp8gWBzIVDsboNqEeLcI6EgxY7gJadPZi44LHBzAfDaSkH6OVpgmLvUuqyC2GCaTGy4mDj/nubT404pjlP+VB6q1gqeBQfoyVl71O8sFwa4wVeqdK6qpJh+rEyhzUWAuR9COuapcq7OIEvCRo3X+8alFxH2dsi5ovFDPMwK09RT/WhnR5Zl2UJtwRDWHd7rl3RnN+C1kQ0E5gkXKwQtx5GrO+aLxR7DY1QO0IJZssjlD4tdGRUswXL3N5t8idCEulqOh2DN5SGxg0lYIAsgTP/sbtYdFVc3Ds+pO8/o0zpEb4TjlKA62Go0VKiCkcuqH25Cs/moo/853dgb6DCC7WBol+p6+UgW+c/EL4uZMa/ESmlsIdLGg="

deploy:
  provider: releases
  api_key:
    secure: fLcBuV72stc6XRexM9uziwwoql9IIeWwSSzs84/PRwKlM7NrQ+wcsBJ+fR8FN4d9uWlHHkb9sw/rpA5KK0u5COd5HVRx56S+mN2DZO1ihZIElJBARAgLzPrNJ69Nm+z4EET+fCwyDwzAwFjrSetF9+QOwmyUO8vllGoM3TZMEhtZU+9OnehErGTYqk0FU6dkXuIv7zoXCzqukMFIK0txq6TdCSOooodRNkdqkHUlPE/8BSnG/RRD2l9qpR2n/rvnVmTpgCLrfxsclb0WfzpHNIZvi45en4GM2a+wRxfM4/F+bap8zufWN4dqp8gWBzIVDsboNqEeLcI6EgxY7gJadPZi44LHBzAfDaSkH6OVpgmLvUuqyC2GCaTGy4mDj/nubT404pjlP+VB6q1gqeBQfoyVl71O8sFwa4wVeqdK6qpJh+rEyhzUWAuR9COuapcq7OIEvCRo3X+8alFxH2dsi5ovFDPMwK09RT/WhnR5Zl2UJtwRDWHd7rl3RnN+C1kQ0E5gkXKwQtx5GrO+aLxR7DY1QO0IJZssjlD4tdGRUswXL3N5t8idCEulqOh2DN5SGxg0lYIAsgTP/sbtYdFVc3Ds+pO8/o0zpEb4TjlKA62Go0VKiCkcuqH25Cs/moo/853dgb6DCC7WBol+p6+UgW+c/EL4uZMa/ESmlsIdLGg=
  file: $TRAVIS_BUILD_DIR/target/topology-*.zip
  skip_cleanup: true
  on:
    repo: bahaaldine/topology
    tags: true
    node: 6.9.0

after_success:
- |2-

  $(npm bin)/set-up-ssh --key "$encrypted_5f819ac0d0f8_key" \
                        --iv "$encrypted_5f819ac0d0f8_iv" \
                        --path-encrypted-key ".travis/github_deploy_key.enc"
