language: node_js
node_js:
- 6.9.0
script:
- gulp build
- gulp package

deploy:
  provider: releases
  api_key:
    secure: gdCQfwnEFacIZcAYef3ZYE0CbLgDW4eDi7D1yu/6g3mRmEarHg6XmGIJASk5Qi5qeMbx9oRAq2alkbNs6RT0G5JSeOG+qF4bBfcNt0vCjWraRNyr0y9c0rjg+oAnYweQyst1L27w2MZLZxvV6sHUFtx2sHDu5sOkAVgZ7RkRaDJElBf4ShxUlOWLYhygGQaRvi868Rr5nJdJn51fKqsJBJODyV/eSo9uGyeP+ix+j9KInDME7dpFtiGNDhxgxm51/sDT4IlyFl67F31snA7fcCxvNwpHbeSqrTQdgVFq7NTiq/W5Ig8LQwqzV0WaxyXbur79UVQk6HJ/SG08m1kH0ehZXAsDy3+exoIVJYPOLCp5E3J+HfClApI8ONZ7sXi5Er0vwz+Nm8Oen9nT5GxjmqZMKxV+u6m29SWbPNR0kKUVSX5jpPzmQnQ0qv9Y7ymebK3nj298mGebdELR5SFK5XrSq7jEKzcl4sEynaCRI98H2l4sPpozmu0crPaUTIzmjtkE6Wxn5e9K3uXTSrYzVlNnGcMXJrKo9K9Zv52NITZKZxBJxy2poxMEeLWCgbec+XQImnx52adR6zHrcuPFReMRh7KJ2Bk+ArTapYTop+64hfAKT77iw91+zylag0aBPNnF7/PN+0SFUgiXHLucgE8cwxnNlNFLIRAVu5gbJ9I=
  file: $TRAVIS_BUILD_DIR/target/topology-*.zip
  skip_cleanup: true
  on:
    repo: bahaaldine/topology
    tags: true
    node: 6.9.0
after_success:
- |2-

  $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" \
                        --iv "$encrypted_XXXXXXXXXXXX_iv" \
                        --path-encrypted-key ".travis/github_deploy_key.enc"
